### ISSUE TITLE
Beberapa kesalahan pada URL & API

### ISSUE THREAD

**Issue by udinIMM** [2019-pemrogramanberbasiskerangkakerja-h/secure-gate-system-test#1]
Berikut beberapa kesalahan pada URL & API setelah dilakukan pengujian oleh Kelompok 12 (Cahya, Ilham, Rohana):
> GET /users/:userid	- Get info user (requirement: params: userid)
DELETE /users/:userid	- Delete user (requirement: params: userid)

Parameter salah. Bukan userid, namun seharusnya username
> POST /gates	- add gate (requirement: body: idgate, start, end)
GET /gates	- get all gates
GET /gates/:gateid	- get info gate (requirement: params: gateid)
DELETE /gates/:gateid	- delete gate (requirement: params: gateid)

Request url salah. Seharusnya /gate tidak menggunakan huruf "s"

Untuk URL Rules belum ada APInya. Serta ada bug pada saat login, bug tersebut tidak perlu menginputkan gate namun tetap bisa login.

**Comment by irhammfadhil** [comment]
Utk URL api sudah saya benahi mas, dan utk url rules sdh saya perbarui dokumentasinya. Utk bug login, saya coba di laptop saya jika tidak menginputkan gate maka tdk bisa login.

ngaksesnya di http://10.151.31.98:3000
