### ISSUE TITLE
GET /gate/:gateid - Get Info gate

### ISSUE THREAD

**Issue by cphikmawan** [2019-pemrogramanberbasiskerangkakerja-h/secure-gate-system-test#4]
![image](https://user-images.githubusercontent.com/22592235/58027512-faf61500-7b42-11e9-8cd1-451bc5fb488f.png)

Saya bingung ketika GET GATE BY ID kok yang keluar malah yang lain, harusnya ketika get gate by id kan outputnya jadi gate ini saja

![image](https://user-images.githubusercontent.com/22592235/58027759-896a9680-7b43-11e9-9bce-a84fe73da638.png)

kok malah outputnya jadi 2, kan bingung saya hehe

**Comment by irhammfadhil** [comment]
done
