### ISSUE TITLE
GET /usergateall/:gateid - show the user that can access the specified gates

### ISSUE THREAD

**Issue by cphikmawan** [2019-pemrogramanberbasiskerangkakerja-h/secure-gate-system-test#6]
kalau mencari usergate by gateid nanti dapatnya tidak 1 row, tapi bisa banyak row.
saran saya menampilkan usergate untuk tiap usernya atau lebih tepatnya tiap record

**Comment by irhammfadhil** [comment]
Yang kelima, kami menggunakan skema untuk delete user dan gate Makai id. Untuk user ke gate menggunakan id keduanya karena user bisa memiliki beberapa akses gate dan gate memiliki banyak user
